# Generated by Django 3.0.2 on 2020-01-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('CIBIL_score', models.IntegerField(blank=True, null=True)),
                ('income', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=200, null=True)),
                ('bank', models.CharField(blank=True, max_length=200, null=True)),
                ('Tenure', models.IntegerField(blank=True, null=True)),
                ('Processing_Fees', models.IntegerField(blank=True, null=True)),
                ('loan_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
