# Generated by Django 2.2.10 on 2020-03-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='interest_rate',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
