# Generated by Django 2.2.10 on 2020-03-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_applicant_interest_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='interest_rate',
        ),
        migrations.AddField(
            model_name='policy',
            name='interest_rate',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
