# Generated by Django 3.0.2 on 2020-01-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_policy_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='bank',
            field=models.CharField(blank=True, choices=[('AXIS', 'AXIS'), ('HDFC', 'HDFC'), ('ICICI', 'ICICI')], max_length=200, null=True),
        ),
    ]
