# Generated by Django 3.0.2 on 2020-01-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200131_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_name',
            field=models.CharField(choices=[('Home Loan', 'Home Loan'), ('Car Loan', 'Car Loan'), ('Educational Loan', 'Educational Loan'), ('Personal Loan', 'Personal Loan'), ('Buisness Loan', 'Buisness Loan'), ('Gold Loan', 'Gold Loan')], max_length=200, null=True),
        ),
    ]
